name: Both image Build

on:
 workflow_dispatch:

jobs:
  build:

   runs-on: ubuntu-latest
   strategy:
     matrix:
      node-version: ['18.x']
    
   steps:
   
 
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    # - name: Install Dependencies
    #   run: npm install

    - name: Build  backend Docker Image
      run: |
         cd Backend/
         docker build -t shivang1012/backend .

    - name: Build  frontend Docker Image
      run: |
         cd ..
         cd Frontend/
         docker build -t shivang1012/frontend .

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN}}

    - name: Push  backend Docker Image to Docker Hub
      run: docker push shivang1012/backend

    - name: Push  frontend Docker Image to Docker Hub
      run: docker push shivang1012/frontend

